import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "./components/RQClient";
import ToastContainer from "./components/Toast/ToastContainer";
import { ToastProvider } from "./components/Toast/useToast";
import NavBar from "./components/NavBar/NavBar";
import { headers } from "next/headers";
import { checkAuth } from "./utils/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <title>ShopKart</title>
        <ToastProvider>
          <body>
            <div>
              {children}
              <ToastContainer />
            </div>
            {/* <footer className="bg-gray-800 text-white py-2 mt-12 h-10 bottom-0 right-0 left-0 absolute">
              <div className="container mx-auto px-4 text-center">
                Made with 💙 by shreyas
              </div>
            </footer> */}
          </body>
        </ToastProvider>
      </html>
    </ReactQueryClientProvider>
  );
}
